### ISSUE TITLE
Update syntax and expected output for ksqlDB 0.7.1

### ISSUE THREAD

**Issue by colinhicks** [confluentinc/kafka-tutorials#215]
These ksqlDB tutorials need to be updated. In lieu of creating individual issues, let's edit the description to reflect PRs (see #214 for an example), then check off each once merged.

- [x] tumbling-windows
- [x] finding-distinct #230 
- [x] hopping-windows #237 
- [x] flatten-nested-data #233 
- [x] aggregating-minmax #225
- [x] aggregating-sum #226 
- [x] joining-table-table #228
- [x] joining-stream-stream #227 
- [x] joining-stream-table #229
- [x] rekeying-function #231 
- [x] udf #232 
- [x] aggregating-count #224 
- [X] splitting #223
- [X] merging #222
- [X] serialization #220 
- [X] filtering #218 
- [X] transforming #216 
- [x] rekeying #214

**Comment by colinhicks** [comment]
cdd3747b
